# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170823_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
