# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170823_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='Hint',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
