# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_solution_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='Hint',
            field=models.CharField(max_length=1000),
        ),
    ]
